---
- name: Deploy compose bundles for docker-external
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc240-docker-external
    compose_stacks:
      - nginx
      - tailscale-peer-relay
      - rustdesk
      - ghost
      - dnns
      - kutt
      - wordpress
      - walletpage
