---
- name: Deploy compose bundles for docker-external
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc240-docker-external
    compose_stacks: "{{ build_inventory.services.lxc240_docker_external | dict2items | selectattr('value.enabled') | map(attribute='key') | list }}"
  when: (build_inventory.services.lxc240_docker_external | dict2items | selectattr('value.enabled') | list | length) > 0
