services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TZ=${TZ}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - GENERIC_TIMEZONE=${TZ}
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - /mnt/appdata/docker_volumes/n8n:/home/node/.n8n
