services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - TZ=Europe/London
    volumes:
      - ./prowlarr:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - TZ=Europe/London
    volumes:
      - ./sonarr:/config
      - /media:/media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      - TZ=Europe/London
    volumes:
      - ./radarr:/config
      - /media:/media

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    environment:
      - TZ=Europe/London
    volumes:
      - ./lidarr:/config
      - /media:/media

  readarr:
    image: lscr.io/linuxserver/readarr:latest
    container_name: readarr
    restart: unless-stopped
    ports:
      - "8787:8787"
    environment:
      - TZ=Europe/London
    volumes:
      - ./readarr:/config
      - /media:/media

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8082:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - TZ=Europe/London
    volumes:
      - ./qbittorrent:/config
      - /media/torrents:/downloads
