services:
  aurral:
    image: ghcr.io/lklynet/aurral:latest
    container_name: aurral
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TZ=${TZ}
      - DOWNLOAD_FOLDER=${DOWNLOAD_FOLDER}
      - LIDARR_URL=${LIDARR_URL}
      - LIDARR_API_KEY=${LIDARR_API_KEY} #update API Key when LIDARR installed
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - PUID=1000
      - PGID=1000
    ports:
      - "3000:3000"
    volumes:
      - /mnt/appdata/docker_volumes/aurral:/app/backend/data
      - /mnt/media_pool/torrents:/app/downloads
