services:
  kutt:
    image: kutt/kutt
    ports:
      - "7070:3000"
    env_file:
      - stack.env
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - stack.env
    volumes:
      - kutt-db:/var/lib/postgresql/data

volumes:
  kutt-db:
