services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: rustdesk_tailscale
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - rustdesk-ts-state:/var/lib/tailscale

  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk_id
    command: hbbs
    restart: unless-stopped
    environment:
      - ALWAYS_USE_RELAY=Y
    volumes:
      - rustdesk-data:/root
    network_mode: service:tailscale
    depends_on:
      - tailscale
      - hbbr

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk_relay
    command: hbbr
    restart: unless-stopped
    volumes:
      - rustdesk-data:/root
    network_mode: service:tailscale
    depends_on:
      - tailscale

volumes:
  rustdesk-ts-state:
  rustdesk-data:
