services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8081:80"
    volumes:
      - /mnt/media_pool:/srv
      - /mnt/appdata/docker_volumes/filebrowser/database:/database
