services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: ansible-semaphore
    user: "0"
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - stack.env
    environment:
      SEMAPHORE_DB_DIALECT=${SEMAPHORE_DB_DIALECT}
      SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
    volumes:
      - /mnt/appdata/docker_volumes/semaphore:/var/lib/semaphore