services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "8582:8581"
    volumes:
      - /mnt/appdata/configs/homebridge:/homebridge
