---
- name: Deploy compose bundles for docker-media
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc230-docker-media
    compose_stacks:
      - plex
      - jellyfin
      - jellyswarrm
