variable "ansible_inventory_path" {
  description = "Rendered Ansible inventory path generated by Terraform"
  type        = string
  default     = "${path.module}/../ansible/inventories/production/hosts.ini"
}

variable "ansible_default_user" {
  description = "Default Ansible SSH user for generated hosts"
  type        = string
  default     = "ansible"
}

variable "ai_vm_enabled" {
  description = "Whether to emit the AI VM into the generated Ansible inventory"
  type        = bool
  default     = true
}

variable "ai_vm_inventory_name" {
  description = "Inventory hostname for the AI VM"
  type        = string
  default     = "ai-gpu-01"
}

variable "ai_vm_ip" {
  description = "IPv4 address of the AI VM used for Ansible inventory generation"
  type        = string
  default     = ""
}

variable "ai_vm_ansible_user" {
  description = "SSH user for the AI VM entry in the generated inventory"
  type        = string
  default     = "ansible"
}

variable "ai_vm_groups" {
  description = "Inventory groups that should contain the AI VM"
  type        = list(string)
  default     = ["ai_gpu"]
}

variable "existing_inventory_groups" {
  description = "Optional pre-existing inventory groups and hosts to include in the rendered inventory"
  type = map(map(object({
    ansible_host = string
    ansible_user = optional(string)
    extra_vars   = optional(map(string))
  })))
  default = {}
}
