variable "ansible_inventory_path" {
  description = "Rendered Ansible inventory path generated by Terraform"
  type        = string
  default     = null
  nullable    = true
}

variable "ansible_default_user" {
  description = "Default Ansible SSH user for generated hosts"
  type        = string
  default     = "ansible"
}
