services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    env_file:
      - stack.env
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEBRIDGE_CONFIG_UI=${HOMEBRIDGE_CONFIG_UI}
      - HOMEBRIDGE_CONFIG_UI_PORT=${HOMEBRIDGE_CONFIG_UI_PORT}
      - TZ=${TZ}
    volumes:
      - /mnt/appdata/configs/homebridge:/homebridge