services:
  grist:
    image: gristlabs/grist:latest
    container_name: grist
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8484:8484"
    volumes:
      - ./data:/persist
