nginx_proxy_hosts:
  - server_name: art.wrightwells.com
    upstream: http://10.10.66.110:8080
    certificate: wrightwells

  - server_name: ha.uk.wrightwells.com
    upstream: http://10.10.20.20:8123
    certificate: uk_wrightwells

  - server_name: jellyfin.uk.wrightwells.com
    upstream: http://10.10.20.15:8096
    certificate: uk_wrightwells

  - server_name: jellyfin.wrightwells.com
    upstream: http://10.10.20.201:3000
    certificate: wrightwells

  - server_name: links.wrightwells.com
    upstream: http://10.10.66.110:7070
    certificate: wrightwells

  - server_name: wallet.wrightwells.com
    upstream: http://10.10.66.110:8070
    certificate: wrightwells


#/mnt/appdata/configs/nginx/certs/
#├── wrightwells.com/
#│   ├── fullchain.pem
#│   └── privkey.pem
#└── uk.wrightwells.com/
#    ├── fullchain.pem
#    └── privkey.pem

#/etc/nginx/certs/wrightwells.com/fullchain.pem
#/etc/nginx/certs/wrightwells.com/privkey.pem
#/etc/nginx/certs/uk.wrightwells.com/fullchain.pem
#/etc/nginx/certs/uk.wrightwells.com/privkey.pem