nginx_proxy_hosts:
  - server_name: art.wrightwells.com
    upstream: "http://{{ homelab_site.addressing.first_octet }}.{{ homelab_site.addressing.second_octet }}.{{ homelab_site.addressing.dmz_vlan }}.110:8080"
    certificate: wrightwells

  - server_name: ha.uk.wrightwells.com
    upstream: "http://{{ homelab_site.addressing.first_octet }}.{{ homelab_site.addressing.second_octet }}.{{ homelab_site.addressing.server_vlan }}.20:8123"
    certificate: uk_wrightwells

  - server_name: jellyfin.uk.wrightwells.com
    upstream: "http://{{ homelab_site.addressing.first_octet }}.{{ homelab_site.addressing.second_octet }}.{{ homelab_site.addressing.server_vlan }}.15:8096"
    certificate: uk_wrightwells

  - server_name: jellyfin.wrightwells.com
    upstream: "http://{{ homelab_site.addressing.first_octet }}.{{ homelab_site.addressing.second_octet }}.{{ homelab_site.addressing.server_vlan }}.201:3000"
    certificate: wrightwells

  - server_name: links.wrightwells.com
    upstream: "http://{{ homelab_site.addressing.first_octet }}.{{ homelab_site.addressing.second_octet }}.{{ homelab_site.addressing.dmz_vlan }}.110:7070"
    certificate: wrightwells

  - server_name: wallet.wrightwells.com
    upstream: "http://{{ homelab_site.addressing.first_octet }}.{{ homelab_site.addressing.second_octet }}.{{ homelab_site.addressing.dmz_vlan }}.110:8070"
    certificate: wrightwells


#/mnt/appdata/configs/nginx/certs/
#├── wrightwells.com/
#│   ├── fullchain.pem
#│   └── privkey.pem
#└── uk.wrightwells.com/
#    ├── fullchain.pem
#    └── privkey.pem

#/etc/nginx/certs/wrightwells.com/fullchain.pem
#/etc/nginx/certs/wrightwells.com/privkey.pem
#/etc/nginx/certs/uk.wrightwells.com/fullchain.pem
#/etc/nginx/certs/uk.wrightwells.com/privkey.pem
