services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "2283:2283"
    volumes:
      - /mnt/appdata/docker_volumes/immich:/usr/src/app/upload
      - /mnt/media_pool/photos:/external
