services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8083:8080"
      - "8181:8181"
    volumes:
      - ./config:/config
