services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    ports:
      - "8083:8080"
      - "8181:8181"
    volumes:
      - /mnt/appdata/docker_volumes/calibre:/config
