services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /mnt/appdata/docker_volumes/mosquitto/config:/mosquitto/config
      - /mnt/appdata/docker_volumes/mosquitto/data:/mosquitto/data
      - /mnt/appdata/docker_volumes/mosquitto/log:/mosquitto/log
