---
- name: Deploy compose bundles for docker-services
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc200-docker-services
    compose_stacks:
      - immich
      - owncloud
      - syncthing
