---
- name: Deploy compose bundles for docker-services
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc200-docker-services
    compose_stacks: "{{ build_inventory.services.lxc200_docker_services | dict2items | selectattr('value.enabled') | map(attribute='key') | list }}"
    docker_host_paths:
      - path: /mnt/appdata/docker_volumes/paperless-ngx
      - path: /mnt/appdata/docker_volumes/paperless-ngx/db
      - path: /mnt/appdata/docker_volumes/paperless-ngx/data
      - path: /mnt/appdata/docker_volumes/paperless-ngx/media
      - path: /mnt/appdata/docker_volumes/paperless-ngx/export
      - path: /mnt/appdata/docker_volumes/paperless-ngx/consume
      - path: /mnt/appdata/docker_volumes/syncthing/config
        owner: "{{ docker_app_uid }}"
        group: "{{ docker_app_gid }}"
      - path: /mnt/appdata/syncthing_sync
        owner: "{{ docker_app_uid }}"
        group: "{{ docker_app_gid }}"
  when: (build_inventory.services.lxc200_docker_services | dict2items | selectattr('value.enabled') | list | length) > 0
