services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/appdata/configs/nginx:/etc/nginx/conf.d
      - /mnt/appdata/docker_volumes/nginx/html:/usr/share/nginx/html
