services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
