[firewall]
pfsense ansible_host=dhcp ansible_user=admin

[ai_gpu]
ai-gpu ansible_host=10.10.66.210 ansible_user=ansible

[docker_arr]
docker-arr ansible_host=10.10.66.66 ansible_user=root

[docker_services]
docker-services ansible_host=10.10.66.200 ansible_user=root

[docker_apps]
docker-apps ansible_host=10.10.66.220 ansible_user=root

[docker_media]
docker-media ansible_host=10.10.66.230 ansible_user=root

[docker_external]
docker-external ansible_host=10.10.66.240 ansible_user=root

[infra]
infra-01 ansible_host=10.10.66.250 ansible_user=root

[docker_hosts:children]
docker_arr
docker_services
docker_apps
docker_media
docker_external
infra
