services:
  tailscale-peer-relay:
    image: tailscale/tailscale:latest
    container_name: tailscale-peer-relay
    restart: unless-stopped
    volumes:
      - ts-peer-relay-state:/var/lib/tailscale
    env_file:
      - stack.env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=peer-relay-node
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    network_mode: host

volumes:
  ts-peer-relay-state:
