---
- name: Deploy compose bundles for infra
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc250-infra
    compose_stacks:
      - mqtt
      - homebridge
      - nginx
