---
- name: Deploy compose bundles for infra
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc250-infra
    compose_stacks:
      - mqtt
      - homebridge
    docker_host_paths:
      - path: /mnt/appdata/configs/homebridge
        owner: "{{ docker_app_uid }}"
        group: "{{ docker_app_gid }}"
