services:
  walletpage:
    image: nginx:latest
    container_name: walletpage
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8089:80"
    volumes:
      - ./html:/usr/share/nginx/html
