services:
  walletpage:
    image: nginx:alpine
    container_name: walletpage
    ports:
      - "8070:80"
    volumes:
      - /mnt/appdata/docker_volumes/walletpage:/usr/share/nginx/html:ro
    restart: unless-stopped
