services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8087:80"
    volumes:
      - /mnt/appdata/configs/nginx-infra:/etc/nginx/conf.d
      - /mnt/appdata/docker_volumes/nginx-infra/html:/usr/share/nginx/html
