services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8087:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
