---
- name: Baseline all hosts
  hosts: all
  become: true
  roles:
    - common

- name: Configure Docker hosts
  hosts: docker_hosts
  become: true
  roles:
    - docker_host

- name: Configure Proxmox hosts
  hosts: proxmox_hosts
  become: true
  roles:
    - proxmox_host
