services:
  dnns:
    image: ghcr.io/n00bcodr/dnns:latest
    container_name: dnns
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8090:8080"
    volumes:
      - /mnt/appdata/docker_volumes/dnns:/app/data
