---
vault_openwebui_secret_key: "replace-with-a-long-random-secret"
vault_postgres_password: "replace-me"
vault_api_token: "replace-me"


#cd /opt/HomeLab/ansible
#ansible-vault create inventories/production/group_vars/vault.yml
#or
#ansible-vault encrypt_string 'very-secret-value' --name 'vault_openwebui_secret_key'
