services:
  jellyswarm:
    image: ghcr.io/jellyswarm/jellyswarm:latest
    container_name: jellyswarm
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "5056:5055"
    volumes:
      - ./config:/config
