---
- name: Deploy compose bundles for docker-arr
  ansible.builtin.include_role:
    name: docker
    tasks_from: deploy_compose_bundle.yml
  vars:
    compose_bundle_name: lxc066-docker-arr
    compose_stacks:
      - filebrowser
      - jellyseerr
      - aurral
      - arr-stack
