services:
  finance:
    image: fireflyiii/core:latest
    container_name: finance
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8085:8080"
    volumes:
      - ./data:/var/www/html/storage/upload
