services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8123:8123"
    volumes:
      - /mnt/appdata/configs/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
