services:
  teslamate:
    container_name: teslamate
    image: teslamate/teslamate:1.28.2
    restart: always
    env_file:
      - stack.env
    environment:
     - DATABASE_USER=${DATABASE_USER}
     - DATABASE_PASS=${DATABASE_PASS}
     - DATABASE_NAME=${DATABASE_NAME}
     - DATABASE_HOST=${DATABASE_HOST}
     - MQTT_HOST=${MQTT_HOST}
     - MQTT_USERNAME=${MQTT_USERNAME}
     - MQTT_PASSWORD=${MQTT_PASSWORD}
     - TZ=Europe/London
     - DATABASE_POOL_SIZE=10
     - ENCRYPTION_KEY=${ENCRYPTION_KEY}
     - VIRTUAL_HOST=local
    ports:
     - 4000:4000
    volumes:
     - /mnt/appdata/docker_volumes/teslamate/import:/opt/app/import
  
    cap_drop:
     - all
 
  postgres:
    container_name: teslamate_postgres
    image: postgres:14
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
     - TZ=${TZ}
     - DATABASE_POOL_SIZE=10
    ports:
     - "5432:5432"
    volumes:
     - teslamate-db:/var/lib/postgresql/data

volumes:
  teslamate-db:
