services:
  blinko:
    image: blinko/blinko:latest
    container_name: blinko
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "1111:1111"
    volumes:
      - /mnt/appdata/docker_volumes/blinko:/app/data
