#!/usr/bin/env bash

# apply-lxc-root-password.sh
#
# Run this AFTER Terraform creates LXCs AND after
# proxmox-apply-lxc-postcreate.sh has rebooted them (bootstrap step 7.4 follow-up).
#
# This sets the root password on all LXCs to the hash from the vault file
# (generated by setup-lxc-root-password.sh).
#
# The correct order is:
#   1. setup-lxc-root-password.sh          (BEFORE Terraform -- generates vault file, writes tfvars)
#   2. Terraform creates LXCs               (cloud-init sets the password from tfvars)
#   3. proxmox-apply-lxc-postcreate.sh      (applies features/mounts, reboots LXCs)
#   4. apply-lxc-root-password.sh           (playbook runs on freshly rebooted LXCs)
#
# Step 4 is a verification pass on a fresh build, and actually sets the correct
# password on existing LXCs that were created before the setup script ran.
#
# Usage:
#   ./scripts/apply-lxc-root-password.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VAULT_PASS_FILE="${HOME}/.config/ansible/homelab-vault-pass.txt"

if [[ ! -f "$VAULT_PASS_FILE" ]]; then
  echo "Error: vault password file not found at ${VAULT_PASS_FILE}." >&2
  echo "Run setup-lxc-root-password.sh first, or create the file manually." >&2
  exit 1
fi

echo "Applying LXC root password via Ansible playbook..."

cd "${REPO_ROOT}/ansible"
ANSIBLE_VAULT_PASSWORD_FILE="$VAULT_PASS_FILE" \
  ansible-playbook \
  -i inventories/production/hosts.ini \
  playbooks/lxc-root-password.yml

echo "LXC root password playbook complete."
