services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8088:80"
    volumes:
      - /mnt/appdata/docker_volumes/wordpress:/var/www/html
