services:
  wordpress:
    image: wordpress:6.9.1-php8.2-apache
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - stack.env
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - wordpress_net

  db:
    image: mariadb:10.11.6
    container_name: wordpress_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - stack.env
    volumes:
      - wordpress-db-data:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  wordpress-data:
  wordpress-db-data:

networks:
  wordpress_net:
    driver: bridge
