services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "3001:3000"
    volumes:
      - /mnt/appdata/docker_volumes/grafana:/var/lib/grafana
