services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <--- add this line here!
      - /mnt/appdata/docker_volumes/homarr/appdata:/appdata
    env_file:
      - stack.env
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    ports:
      - '7575:7575'
