services:
  ghost:
    image: ghost:5
    container_name: ghost-art
    restart: unless-stopped
    environment:
      url: http://art.wrightwells.com
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    volumes:
      - /mnt/appdata/docker_volumes/ghost:/var/lib/ghost/content
    ports:
      - "2368:2368"
