services:
  ghost:
    image: ghost:5
    container_name: ghost-art
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      url: "${url}"
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
    volumes:
      - ghost-data:/var/lib/ghost/content
    ports:
      - "2368:2368"

volumes:
  ghost-data:
