---
- name: Deploy docker stacks
  hosts: ai_gpu
  become: true

  roles:
    - role: docker_stack
      vars:
        stack_name: openwebui
        stack_dir: /mnt/appdata/openwebui
        stack_compose_template: compose.yml.j2
        stack_env_template: app.env.j2

        stack_env:
          TZ: "{{ timezone }}"
          OPENWEBUI_PORT: "{{ openwebui_port }}"
          OLLAMA_BASE_URL: "{{ ollama_base_url }}"
          WEBUI_SECRET_KEY: "{{ vault_openwebui_secret_key }}"

        stack_compose:
          published_port: "{{ openwebui_port }}"
          app_data_dir: "/mnt/appdata/openwebui"
