services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8080:8080"
    volumes:
      - ./files:/mnt/data
