services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8084:8083"
    volumes:
      - /mnt/appdata/docker_volumes/calibre-web:/config
      - /mnt/media_pool/books:/books
