services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    ports:
      - "8084:8083"
    volumes:
      - calibre-web-data:/config
      - /mnt/media_pool/books:/books

volumes:
  calibre-web-data:
